"""Client-facing bug report + technical summary from an LQA report.

Implements ~/.claude/skills/localization/bug-report-builder (the skill doc
is the source of truth). The load-bearing rules:

- **Every finding needs a suggested translation** — generated by the
  Repair agent (glossary-pinned), EXCEPT sources that are already
  English/numeric/code tokens, which instead get an auto Orbit8 Comment
  asking the dev to validate ("a blank suggestion is always explained,
  never just missing").
- **Round-trip safety** — Status / Dev Feedback / Assigned To /
  Last Updated / Orbit8 Comment are human-owned columns. Rebuilds read the
  existing workbook, merge those back by String ID, and back up the prior
  file first. Auto-generated comments carry the AUTO_NOTE prefix so they
  refresh from code instead of masquerading as reviewer input.
- Category tokens map to client-facing labels; the raw token stays in the
  Description for round-trip parsing.
"""
from __future__ import annotations

import shutil
from datetime import date
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from . import agents
from .glossary import Glossary
from .llm import Provider
from .schemas import (BugType, Finding, LQAItem, LQAReport, Severity,
                      StyleBrief)

# internal token -> client-facing label (raw token stays in Description)
CATEGORY_LABELS = {
    "placeholder": "Localization - Tag/Markup",
    "markup": "Localization - Tag/Markup",
    "terminology": "Localization - Terminology",
    "untranslated": "Localization - Untranslated",
    "leakage": "Localization - Source Leakage",
    "mistranslation": "Localization - Mistranslation",
    "omission": "Localization - Omission",
    "grammar": "Localization - Grammar",
    "register": "Localization - Tone/Register",
    "length": "Localization - Length/Truncation",
    "punctuation": "Localization - Punctuation",
    "compliance": "Compliance",
    "consistency": "Localization - Terminology Inconsistency",
    "regression": "Localization - Regression",
}

SEVERITY_LABELS = {Severity.HIGH: "HIGH", Severity.MEDIUM: "MEDIUM",
                   Severity.LOW: "LOW"}
SEVERITY_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}
SEVERITY_FILL = {"CRITICAL": "FF9999", "HIGH": "FFC7A0",
                 "MEDIUM": "FFE699", "LOW": "D9EAD3"}

HEADERS = ["Bug#", "Date Reported", "Category - Summary", "Description",
           "Location/String ID", "Source Text", "Current Translation",
           "Expected Result / Suggested Translation", "Severity", "Status",
           "Dev Feedback", "Assigned To", "Last Updated", "Orbit8 Comment"]
HUMAN_COLUMNS = ["Status", "Dev Feedback", "Assigned To", "Last Updated",
                 "Orbit8 Comment"]

AUTO_NOTE = "AUTO: "
CODE_TOKEN_NOTE = (AUTO_NOTE + "source looks like a code/name token — "
                   "validate with dev whether it is intentionally kept "
                   "as-is")


def is_code_token(source: str) -> bool:
    """English word / number / identifier that may legitimately stay
    untranslated (skill: the ONLY findings allowed a blank suggestion)."""
    stripped = source.strip()
    if not stripped or len(stripped) > 24 or " " in stripped:
        return False
    return all(ch.isascii() and (ch.isalnum() or ch in "_-.%")
               for ch in stripped)


def suggestion_exempt(item: LQAItem) -> bool:
    """Blank suggestion is allowed ONLY for code/name tokens whose sole
    complaint is being untranslated — a terminology finding on the same
    token still has a locked rendering and MUST get a suggestion."""
    return is_code_token(item.source) and all(
        vf.finding.bug_type == BugType.UNTRANSLATED
        for vf in item.findings)


def build_suggestions(provider: Optional[Provider], items: List[LQAItem], *,
                      game: str, source_lang: str, locale: str,
                      glossary: Optional[Glossary] = None,
                      style_brief: Optional[StyleBrief] = None,
                      style_guide=None, gate_cfg=None,
                      domains: Optional[Dict[str, str]] = None,
                      batch_size: int = 8,
                      rejected: Optional[List[dict]] = None
                      ) -> Dict[str, str]:
    """Glossary-pinned corrected translations via the Repair agent.

    A suggestion ships to the client, so it is held to the SAME standard
    as a delivery: after generation each candidate is re-run through the
    deterministic gate (glossary + mechanical style rules). A suggestion
    that still violates a rule gets one repair retry; if it still fails
    it is DROPPED rather than shipped — proposing a fix that breaks
    another rule is worse than proposing none, and the reviewer sees the
    finding either way. Rejections are appended to ``rejected`` so the
    run can report them.
    """
    todo = [i for i in items if not suggestion_exempt(i)]
    if provider is None or not todo:
        return {}
    domains = domains or {}

    def _violations(item: LQAItem, candidate: str) -> List[Finding]:
        """Deterministic re-check of a proposed fix."""
        if gate_cfg is None:
            return []
        from .gate_checks import run_gate
        return run_gate(item.uid, item.source, candidate, gate_cfg,
                        domain=domains.get(item.uid))

    suggestions: Dict[str, str] = {}
    for start in range(0, len(todo), batch_size):
        batch = todo[start:start + batch_size]
        flagged: List[Tuple[str, str, str, List[Finding]]] = [
            (i.uid, i.source, i.target, [vf.finding for vf in i.findings])
            for i in batch]
        brief = (glossary.brief_for([i.source for i in batch])
                 if glossary else None)
        batch_domains = {domains.get(i.uid) for i in batch}
        repaired, _fp = agents.repair_batch(
            provider, flagged, source_lang=source_lang, target_lang=locale,
            game=game, glossary_brief=brief, style_brief=style_brief,
            style_guide=style_guide,
            domain=(batch_domains.pop() if len(batch_domains) == 1
                    else None))
        by_uid = {i.uid: i for i in batch}
        retry: List[Tuple[str, str, str, List[Finding]]] = []
        for item in repaired.items:
            candidate = item.target_text.strip()
            if not candidate:
                continue
            source_item = by_uid.get(item.key)
            if source_item is None:
                continue
            problems = _violations(source_item, candidate)
            if not problems:
                suggestions[item.key] = candidate
            else:
                retry.append((item.key, source_item.source, candidate,
                              problems))
        if not retry:
            continue
        # one corrective pass: the repair broke a rule it was told to keep
        retry_brief = (glossary.brief_for(
            [src for _k, src, _c, _f in retry]) if glossary else None)
        second, _fp = agents.repair_batch(
            provider, retry, source_lang=source_lang, target_lang=locale,
            game=game, glossary_brief=retry_brief,
            style_brief=style_brief, style_guide=style_guide)
        for item in second.items:
            candidate = item.target_text.strip()
            source_item = by_uid.get(item.key)
            if not candidate or source_item is None:
                continue
            problems = _violations(source_item, candidate)
            if problems:
                if rejected is not None:
                    rejected.append({
                        "uid": item.key, "source": source_item.source,
                        "candidate": candidate,
                        "violations": [f.message for f in problems]})
                continue                      # never ship a bad fix
            suggestions[item.key] = candidate
    return suggestions


def load_locations(path: Path) -> Dict[str, str]:
    """key -> location map for _location, from a .po (UE ``#:`` reference
    comments) or a bilingual pairs .jsonl carrying a ``location`` field."""
    import json
    locations: Dict[str, str] = {}
    if Path(path).suffix.lower() == ".po":
        from .exports import read_po_entries
        for key, _source, _target, location in read_po_entries(Path(path)):
            if location:
                locations[key] = location
    else:
        for line in Path(path).read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            row = json.loads(line)
            if row.get("location"):
                locations[row["key"]] = row["location"]
    return locations


def _location(item: LQAItem,
              locations: Optional[Dict[str, str]] = None) -> str:
    """String ID column. With a locations map, each game key renders as
    ``<UE widget/asset path> :: <key>`` so the dev lands on the actual
    widget instead of an opaque GUID."""
    def render(key: str) -> str:
        loc = (locations or {}).get(key)
        return f"{loc} :: {key.lstrip(',')}" if loc else key
    joiner = " ; " if locations else ","
    keys = joiner.join(render(k) for k in item.game_keys[:3])
    if len(item.game_keys) > 3:
        keys += f",+{len(item.game_keys) - 3}"
    return f"{item.uid} :: {keys}"


def _read_human_columns(path: Path) -> Dict[str, Dict[str, str]]:
    """Existing workbook → {String ID: {human column: value}}."""
    if not path.exists():
        return {}
    import openpyxl
    sheet = openpyxl.load_workbook(path).active
    rows = list(sheet.iter_rows(values_only=True))
    if not rows or list(rows[0][:len(HEADERS)]) != HEADERS:
        return {}
    kept: Dict[str, Dict[str, str]] = {}
    idx = {name: i for i, name in enumerate(HEADERS)}
    for row in rows[1:]:
        location = row[idx["Location/String ID"]]
        if not location:
            continue
        values = {}
        for column in HUMAN_COLUMNS:
            value = row[idx[column]]
            if value in (None, ""):
                continue
            if (column == "Orbit8 Comment"
                    and str(value).startswith(AUTO_NOTE)):
                continue                    # auto notes refresh from code
            if column == "Status" and value == "New":
                continue
            values[column] = str(value)
        if values:
            kept[str(location)] = values
    return kept


def write_bug_report_xlsx(report: LQAReport, path: Path, *,
                          suggestions: Dict[str, str], game: str,
                          locations: Optional[Dict[str, str]] = None
                          ) -> int:
    """One workbook per locale, severity-sorted, color-coded, round-trip
    safe. Returns the number of bug rows."""
    import openpyxl
    from openpyxl.styles import Alignment, Font, PatternFill

    preserved = _read_human_columns(path)
    if path.exists():
        shutil.copyfile(path, path.with_suffix(".bak.xlsx"))

    rows = []
    for item in report.items:
        for vf in item.findings:
            finding = vf.finding
            severity = SEVERITY_LABELS[finding.severity]
            token = finding.bug_type.value
            suggestion = suggestions.get(item.uid, "")
            comment = ""
            if not suggestion and suggestion_exempt(item):
                comment = CODE_TOKEN_NOTE
            description = f"{finding.message} [{token}]"
            if vf.verdict and vf.verdict.reasoning:
                description += f" | reviewer: {vf.verdict.reasoning}"
            rows.append({
                "Category - Summary": CATEGORY_LABELS.get(
                    token, f"Localization - {token.title()}"),
                "Description": description,
                "Location/String ID": _location(item, locations),
                "Source Text": item.source,
                "Current Translation": item.target,
                "Expected Result / Suggested Translation": suggestion,
                "Severity": severity, "Status": "New",
                "Orbit8 Comment": comment,
            })
    rows.sort(key=lambda r: (SEVERITY_ORDER[r["Severity"]],
                             r["Location/String ID"]))

    book = openpyxl.Workbook()
    sheet = book.active
    sheet.title = f"{game} LQA {report.locale}"
    sheet.append(HEADERS)
    for cell in sheet[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", start_color="333F50")
        cell.alignment = Alignment(vertical="center")
    today = date.today().isoformat()
    for number, row in enumerate(rows, 1):
        row.update({"Bug#": number, "Date Reported": today})
        kept = preserved.get(row["Location/String ID"], {})
        for column, value in kept.items():
            row[column] = value
        sheet.append([row.get(h, "") for h in HEADERS])
        fill = PatternFill("solid",
                           start_color=SEVERITY_FILL[row["Severity"]])
        sheet.cell(row=number + 1,
                   column=HEADERS.index("Severity") + 1).fill = fill
    widths = {"Description": 60, "Source Text": 40,
              "Current Translation": 40,
              "Expected Result / Suggested Translation": 40,
              "Location/String ID": 34, "Orbit8 Comment": 30}
    for name, width in widths.items():
        letter = sheet.cell(row=1,
                            column=HEADERS.index(name) + 1).column_letter
        sheet.column_dimensions[letter].width = width
    path.parent.mkdir(parents=True, exist_ok=True)
    book.save(path)
    return len(rows)


def write_tech_summary(report: LQAReport, path: Path, *, game: str,
                       split_counts: Optional[Dict[str, int]] = None,
                       suggestions_count: int = 0) -> None:
    flag_rate = (report.flagged_strings / report.checked * 100
                 if report.checked else 0.0)
    lines = [
        f"# {game} — LQA Technical Summary ({report.locale})",
        f"Date: {date.today().isoformat()} · job `{report.job_id}`", "",
        "## Corpus",
        f"- unique strings checked: **{report.checked}**",
    ]
    if split_counts:
        lines.append(f"- batch split (docs/skills/lqa-batch-split.md): "
                     f"story {split_counts.get('story', 0)} (n=5) · "
                     f"strings {split_counts.get('string', 0)} (n=20)")
    led = report.cascade_ledger
    if led:
        lines += [
            "", "## Cascade audit (T1 → T2 → T3 → verify)",
            f"- accepted {led.get('accepted')} → T1 flagged "
            f"{led.get('t1_flagged')} → T2 saw {led.get('t2_input')}, "
            f"flagged {led.get('t2_flagged')} → T3 saw "
            f"{led.get('t3_input')}"
            + (f", raised {led.get('t3_raw')} findings, "
               f"{led.get('t3_kept')} survived second-layer review"
               if led.get("t3_ran") else " (tier 3 not run)"),
            "- ledger written by the cascade nodes themselves and "
            "validated (verify_cascade) before this report could be "
            "produced",
        ]
    lines += [
        "", "## Results",
        f"- flagged: **{report.flagged_strings}** strings "
        f"({flag_rate:.1f}%), {report.findings_total} findings",
        f"- confirmed {report.confirmed} · overturned {report.overturned} "
        f"· uncertain {report.uncertain}",
        f"- suggested fixes generated: {suggestions_count}",
        f"- ship verdict: "
        f"{'✋ **BLOCK SHIP**' if report.block_ship else '✅ pass'}", "",
        "## Findings by severity",
        "| Severity | Count |", "|---|---|",
    ]
    for severity, count in sorted(report.by_severity.items()):
        lines.append(f"| {severity.upper()} | {count} |")
    lines += ["", "## Findings by category",
              "| Category | Internal token | Count |", "|---|---|---|"]
    for token, count in sorted(report.by_bug_type.items(),
                               key=lambda kv: -kv[1]):
        label = CATEGORY_LABELS.get(token, token)
        lines.append(f"| {label} | `{token}` | {count} |")
    lines += ["", "## Reading guide",
              "- Terminology findings are judged against the LOCKED "
              "glossary; translations predating the lock are expected to "
              "flag — they are the retrofit backlog, not translator "
              "error.",
              "- Blank suggestions always carry an Orbit8 Comment "
              "explaining why (code/name tokens needing dev validation)."]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
