"""In-game test kit emitter (docs/STANDARDS.md §4.5).

The kit is what a tester takes into the build: every string in scope, with
the LQA side's risk prediction attached, and empty TEST_* columns they fill
while playing. Same family as the PE forms (§4.1–4.3) — agent-authored
columns come back unchanged, human columns are emitted empty with dropdowns
pre-attached so the returning document parses deterministically.

Three owners, unlike the PE forms, and the prefix says which:

  (none)  agent, deterministic — StringID/StringType/Source from the corpus
  AI_*    agent, model-predicted — advisory; the tester's verdict outranks it
  TEST_*  the tester, in-game

Design rules that are load-bearing:

- **Every string ships, predicted-risk or not.** Filtering the kit down to
  AI_ExpectedBug=Yes would make a missed prediction structurally invisible —
  no one would ever look at the row. Risk-first ordering gets the same
  prioritization without the blind spot.
- **The prediction vocabulary is the bug report's vocabulary**
  (TEST_ERROR_TYPES). Predictions and confirmed bugs are then countable
  against each other, which is the only way prediction quality is ever
  measurable.
- **A blank TEST_Decision means "not tested", never "no issue"** — "No Issue"
  is an affirmative result the tester must select. Coverage is a real number
  only if those two stay distinct.
"""
from __future__ import annotations

from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence

from .standards import (FORM_DROPDOWNS, TEST_ERROR_TYPES,
                        TEST_ERROR_TYPE_BY_TOKEN, TEST_FILLED_COLUMNS,
                        TEST_KIT_FORM_HEADERS)

# Multi-value separator for AI_ErrorTypes. Semicolon, not comma: error type
# labels ("Tag/Markup") are safe but a tester pasting prose into a cell is
# not, and the reader must never split a sentence on its punctuation.
ERROR_TYPE_SEP = "; "

# Risk-first ordering: predicted bugs to the top so a tester who runs out of
# time has covered the highest-value rows.
_RISK_FILL = "FFE699"          # amber — AI_ExpectedBug = Yes
_HEADER_AGENT = "333F50"       # slate — agent columns (matches the PE forms)
_HEADER_AI = "5B6E8C"          # lighter slate — AI_* predictions
_HEADER_TEST = "1F6F43"        # green — the tester's columns

_GUIDE = (
    "IN-GAME TEST KIT — how to fill",
    "",
    "Fill ONLY the TEST_* columns (green headers). Every other column is "
    "generated by the LQA team and must come back unchanged — we match your "
    "results back by StringID.",
    "",
    "WHAT THE COLUMNS MEAN",
    "  StringID / StringType / StringLocation — where the string lives in "
    "the build. Use these to find it in game.",
    "  Source / Target_Current — the original text and what is currently "
    "shown in the localized build.",
    "  AI_ExpectedBug — our prediction that this string needs extra "
    "attention. A HINT, NOT A VERDICT.",
    "  AI_ErrorTypes — what we predict could go wrong here "
    "(multiple values separated by '; ').",
    "",
    "IMPORTANT: AI_ExpectedBug = No does NOT mean the string is fine. "
    "If you see a problem on a 'No' row, report it — those are the most "
    "valuable finds, because our prediction missed them.",
    "",
    "HOW TO FILL",
    "  TEST_Decision (dropdown) — REQUIRED for every row you test:",
    "    No Issue                  — you checked it in game; it displays "
    "correctly.",
    "    Localization Bug          — wrong/awkward translation, terminology, "
    "tone.",
    "    Internationalization Bug  — the TEXT is fine but the BUILD breaks "
    "it: overflow, clipping, garbled characters, broken placeholder.",
    "    Needs Investigation       — something is off but you cannot tell "
    "what; explain in TEST_Notes.",
    "    Cannot Reproduce          — you could not reach or trigger this "
    "string.",
    "",
    "  Leave TEST_Decision BLANK only if you did not test the row. "
    "Blank = not tested; it is NOT the same as 'No Issue'.",
    "",
    "  TEST_Reproduction — REQUIRED when you report either bug type. "
    "Numbered steps from a known state, e.g. "
    "'1. New game  2. Ch.1 first battle  3. Open skill panel'.",
    "  TEST_Context — GM command, chapter, quest, or map location that gets "
    "us back to the string fastest. A screenshot filename works too.",
    "  TEST_AssignedTeam (dropdown) — who should own the fix. "
    "Localization for wording; Engineering/UI for display and layout.",
    "  TEST_Suggestion — optional; your proposed wording if you are "
    "reporting a localization issue.",
    "  TEST_Notes — anything else: what you saw, device/resolution, "
    "screenshot reference.",
    "",
    "Rows highlighted in amber are the ones we predict are risky. "
    "Start there if you are short on time, then sweep the rest.",
)


def normalize_error_types(values: Optional[Iterable[str]]) -> str:
    """Render predicted error types as one cell, validating the vocabulary.

    An unrecognized label is a bug in the caller, not a tester problem, so
    it fails loudly here rather than shipping a value no downstream reader
    can aggregate. Accepts internal bug_report tokens ("placeholder") as
    well as kit labels ("Tag/Markup") so callers can pass findings through
    untranslated. Order is preserved, duplicates dropped."""
    if not values:
        return ""
    out: List[str] = []
    for raw in values:
        value = str(raw).strip()
        if not value:
            continue
        label = TEST_ERROR_TYPE_BY_TOKEN.get(value.lower(), value)
        if label not in TEST_ERROR_TYPES:
            raise ValueError(
                f"unknown predicted error type {raw!r}; expected one of "
                f"{TEST_ERROR_TYPES} (or a bug_report token)")
        if label not in out:
            out.append(label)
    return ERROR_TYPE_SEP.join(out)


def emit_test_kit(path: Path, rows: List[Dict[str, str]], *,
                  extra_columns: Sequence[str] = (),
                  risk_first: bool = True) -> int:
    """Write the test kit workbook (§4.5).

    ``rows`` carry the agent-authored columns; TEST_* values are ignored —
    they belong to the tester. ``AI_ErrorTypes`` accepts either a
    pre-joined string or a list of labels/tokens. ``extra_columns`` appends
    agent-authored context AFTER the standard block, so the standard shape
    is extended, never altered. With ``risk_first`` the predicted-bug rows
    sort to the top (stable within each group). Returns the row count."""
    import openpyxl
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.worksheet.datavalidation import DataValidation

    headers = list(TEST_KIT_FORM_HEADERS)
    for column in extra_columns:
        if column in headers:
            raise ValueError(f"extra column {column!r} collides with the "
                             f"standard test kit form")
        headers.append(column)

    ordered = list(rows)
    if risk_first:
        # Stable: preserves the caller's ordering (usually corpus order)
        # inside the Yes block and inside the No block.
        ordered.sort(key=lambda r: 0 if _is_expected_bug(r) else 1)

    book = openpyxl.Workbook()
    sheet = book.active
    sheet.title = "Test Kit"
    sheet.append(headers)
    for cell in sheet[1]:
        name = str(cell.value)
        fill = (_HEADER_TEST if name in TEST_FILLED_COLUMNS
                else _HEADER_AI if name.startswith("AI_") else _HEADER_AGENT)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", start_color=fill)
        cell.alignment = Alignment(vertical="center", wrap_text=True)

    for row in ordered:
        values = []
        for header in headers:
            if header in TEST_FILLED_COLUMNS:
                values.append("")            # the tester's column
            elif header == "AI_ErrorTypes":
                raw = row.get(header, "")
                values.append(raw if isinstance(raw, str)
                              else normalize_error_types(raw))
            else:
                values.append(row.get(header, ""))
        sheet.append(values)
        if _is_expected_bug(row):
            sheet.cell(row=sheet.max_row, column=1).fill = PatternFill(
                "solid", start_color=_RISK_FILL)

    last = max(len(ordered), 1) + 1
    for col, options in FORM_DROPDOWNS["testkit"].items():
        if col not in headers:
            continue
        validation = DataValidation(
            type="list", formula1='"' + ",".join(options) + '"',
            allow_blank=True, showDropDown=False)
        sheet.add_data_validation(validation)
        letter = sheet.cell(row=1, column=headers.index(col) + 1).column_letter
        validation.add(f"{letter}2:{letter}{last}")

    widths = {"StringID": 34, "StringType": 12, "StringLocation": 30,
              "Source": 45, "Target_Current": 45,
              "AI_ExpectedBug": 14, "AI_ErrorTypes": 28,
              "TEST_Reproduction": 40, "TEST_Context": 26,
              "TEST_AssignedTeam": 18, "TEST_Decision": 26,
              "TEST_Suggestion": 40, "TEST_Notes": 36}
    for name, width in widths.items():
        if name in headers:
            letter = sheet.cell(
                row=1, column=headers.index(name) + 1).column_letter
            sheet.column_dimensions[letter].width = width
    sheet.freeze_panes = "F2"                # keep the string visible while
                                             # filling the TEST_* columns
    sheet.auto_filter.ref = f"A1:{sheet.cell(row=1, column=len(headers)).column_letter}{last}"

    guide = book.create_sheet("说明 How to fill")
    for line in _GUIDE:
        guide.append([line])
    guide.column_dimensions["A"].width = 100
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    book.save(path)
    return len(ordered)


def _is_expected_bug(row: Dict[str, str]) -> bool:
    return str(row.get("AI_ExpectedBug", "")).strip().lower() == "yes"
